// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Application: typeof import('./components/Application/Application.vue')['default']
    BasicForm: typeof import('./components/Form/src/BasicForm.vue')['default']
    BasicModal: typeof import('./components/Modal/src/basicModal.vue')['default']
    BasicUpload: typeof import('./components/Upload/src/BasicUpload.vue')['default']
    ColumnSetting: typeof import('./components/Table/src/components/settings/ColumnSetting.vue')['default']
    CountTo: typeof import('./components/CountTo/CountTo.vue')['default']
    DialogContent: typeof import('./components/DialogContent/index.vue')['default']
    EditableCell: typeof import('./components/Table/src/components/editable/EditableCell.vue')['default']
    LoadingContent: typeof import('./components/LoadingContent/index.vue')['default']
    Lockscreen: typeof import('./components/Lockscreen/Lockscreen.vue')['default']
    MessageContent: typeof import('./components/MessageContent/index.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NBadge: typeof import('naive-ui')['NBadge']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Recharge: typeof import('./components/Lockscreen/Recharge.vue')['default']
    Table: typeof import('./components/Table/src/basic-table.vue')['default']
    TableAction: typeof import('./components/Table/src/components/TableAction.vue')['default']
  }
}

export { }
