// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddBaseTypes: typeof import('./src/components/base-types/components/add-base-types.vue')['default']
    Application: typeof import('./src/components/application/application.vue')['default']
    BaseTypes: typeof import('./src/components/base-types/index.vue')['default']
    BasicForm: typeof import('./src/components/form/src/basic-form.vue')['default']
    BasicModal: typeof import('./src/components/modal/src/basic-modal.vue')['default']
    BasicTable: typeof import('./src/components/table/src/basic-table.vue')['default']
    BasicUpload: typeof import('./src/components/upload/src/basic-upload.vue')['default']
    ColumnSetting: typeof import('./src/components/table/src/components/settings/column-setting.vue')['default']
    CountTo: typeof import('./src/components/count-to/count-to.vue')['default']
    CustomFormUse: typeof import('./src/components/custom-form-use/index.vue')['default']
    DialogContent: typeof import('./src/components/dialog-content/index.vue')['default']
    EditableCell: typeof import('./src/components/table/src/components/editable/editable-cell.vue')['default']
    FlowChart: typeof import('./src/components/flow-chart/flow-chart.vue')['default']
    LoadingContent: typeof import('./src/components/loading-content/index.vue')['default']
    LockScreen: typeof import('./src/components/lock-screen/lock-screen.vue')['default']
    MainHeader: typeof import('./src/components/main-header/index.vue')['default']
    MessageContent: typeof import('./src/components/message-content/index.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
  }
}
